using System.Text;
using VeracodeRemediation.Core.Interfaces;
using VeracodeRemediation.Core.Models;

namespace VeracodeRemediation.Application.Generators;

/// <summary>
/// Generates markdown remediation reports
/// </summary>
public class ReportGenerator : IReportGenerator
{
    public async Task<string> GenerateReportAsync(
        RemediationReport report,
        string outputPath,
        CancellationToken cancellationToken = default)
    {
        var markdown = new StringBuilder();

        // Header
        markdown.AppendLine("# Veracode Security Remediation Report");
        markdown.AppendLine();
        markdown.AppendLine($"**Generated:** {report.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
        markdown.AppendLine($"**Total Vulnerabilities:** {report.TotalVulnerabilities}");
        markdown.AppendLine();

        // Summary
        markdown.AppendLine("## Summary");
        markdown.AppendLine();
        markdown.AppendLine($"- ✅ **Auto-fixed:** {report.AutoFixed.Count}");
        markdown.AppendLine($"- ⚠️ **Requires Manual Review:** {report.RequiresManualReview.Count}");
        markdown.AppendLine($"- ⏭️ **Skipped:** {report.Skipped.Count}");
        markdown.AppendLine();

        // Auto-fixed vulnerabilities
        if (report.AutoFixed.Any())
        {
            markdown.AppendLine("## ✅ Automatically Fixed Vulnerabilities");
            markdown.AppendLine();
            markdown.AppendLine("The following vulnerabilities were automatically fixed:");
            markdown.AppendLine();
            markdown.AppendLine("| ID | CWE | Severity | File | Fix Description |");
            markdown.AppendLine("|----|-----|----------|------|-----------------|");

            foreach (var vuln in report.AutoFixed)
            {
                markdown.AppendLine($"| {vuln.Id} | {vuln.CweId} | {vuln.Severity} | `{vuln.FilePath}` | {vuln.FixDescription ?? "N/A"} |");
            }

            markdown.AppendLine();
        }

        // Manual review required
        if (report.RequiresManualReview.Any())
        {
            markdown.AppendLine("## ⚠️ Vulnerabilities Requiring Manual Review");
            markdown.AppendLine();
            markdown.AppendLine("The following vulnerabilities require manual review and cannot be automatically fixed:");
            markdown.AppendLine();
            markdown.AppendLine("| ID | CWE | Severity | File | Reason |");
            markdown.AppendLine("|----|-----|----------|------|--------|");

            foreach (var vuln in report.RequiresManualReview)
            {
                markdown.AppendLine($"| {vuln.Id} | {vuln.CweId} | {vuln.Severity} | `{vuln.FilePath}` | {vuln.Reason ?? "N/A"} |");
            }

            markdown.AppendLine();
        }

        // Skipped vulnerabilities
        if (report.Skipped.Any())
        {
            markdown.AppendLine("## ⏭️ Skipped Vulnerabilities");
            markdown.AppendLine();
            markdown.AppendLine("The following vulnerabilities were skipped:");
            markdown.AppendLine();
            markdown.AppendLine("| ID | CWE | Severity | File | Reason |");
            markdown.AppendLine("|----|-----|----------|------|--------|");

            foreach (var vuln in report.Skipped)
            {
                markdown.AppendLine($"| {vuln.Id} | {vuln.CweId} | {vuln.Severity} | `{vuln.FilePath}` | {vuln.Reason ?? "N/A"} |");
            }

            markdown.AppendLine();
        }

        // Patch file reference
        if (!string.IsNullOrWhiteSpace(report.PatchFilePath))
        {
            markdown.AppendLine("## 📦 Patch File");
            markdown.AppendLine();
            markdown.AppendLine($"A patch file has been generated at: `{report.PatchFilePath}`");
            markdown.AppendLine();
            markdown.AppendLine("To apply the patch:");
            markdown.AppendLine("```bash");
            markdown.AppendLine($"git apply {report.PatchFilePath}");
            markdown.AppendLine("```");
            markdown.AppendLine();
        }

        // Next steps
        markdown.AppendLine("## 📋 Next Steps");
        markdown.AppendLine();
        markdown.AppendLine("1. **Review the patch file** - Ensure all changes are correct");
        markdown.AppendLine("2. **Test the fixes** - Run your test suite to verify no breaking changes");
        markdown.AppendLine("3. **Apply the patch** - Use `git apply` or review the changes in your IDE");
        markdown.AppendLine("4. **Manual fixes** - Address vulnerabilities marked for manual review");
        markdown.AppendLine("5. **Re-scan** - Run Veracode scan again to verify fixes");
        markdown.AppendLine();

        // Footer
        markdown.AppendLine("---");
        markdown.AppendLine();
        markdown.AppendLine("*This report was generated by Veracode Remediation Automation*");

        var fullPath = Path.IsPathRooted(outputPath)
            ? outputPath
            : Path.Combine(Directory.GetCurrentDirectory(), outputPath);

        var directory = Path.GetDirectoryName(fullPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllTextAsync(fullPath, markdown.ToString(), cancellationToken);
        return fullPath;
    }
}

